<?php
namespace Shadiyarovs;
require "children.php";

class Grandchildren extends Children {

    public function ParentsSalary()
    {
        parent::ParentsSalary(); // TODO: Change the autogenerated stub
    }

}

$obj = new Grandchildren();
echo $obj->ParentsSalary();


