<?php
$fruites1 = [
    'apple',
    'pear',
    'orange',
    'banana',
    'kiwi',
    'pomogranate',
    'strawberry',
    'lime',
    'lemon',
    'blueberry',
    'rawberry',
    'grapes',
    'coconuts',
    'pineapples',
    'watermelon',
    'melon',
    'mandarin',
    'peach',
    'plum',
    'cherry',
    'blackerry',
    'apricot',
    'dragon fruits',
    'dades',
    'mango',
    'fig',
    'mallberry',
    'papaya',
    'grapefruites',
    'guava',
    'starfruite',
    'crunberry',
    'rose hip',
];
$fruites2 = [
    'apple',
    'pear',
    'orange',
    'banana',
    'kiwi',
    'pomogranate',
    'strawberry',
    'lime',
    'lemon',
    'blueberry',
    'rawberry',
    'grapes',
    'coconuts',
    'pineapples',
    'watermelon',
    'melon',
    'mandarin',
    'peach',
    'plum',
    'cherry',
    'blackerry',
    'apricot',
    'dragon fruits',
    'dades',
    'mango',
    'fig',
    'mallberry',
    'papaya',
    'grapefruites',
    'guava',
    'starfruite',
    'crunberry',
    'rose hip',
];
$fruites3 = [
    'apple',
    'pear',
    'orange',
    'banana',
    'kiwi',
    'pomogranate',
    'strawberry',
    'lime',
    'lemon',
    'blueberry',
    'rawberry',
    'grapes',
    'coconuts',
    'pineapples',
    'watermelon',
    'melon',
    'mandarin',
    'peach',
    'plum',
    'cherry',
    'blackerry',
    'apricot',
    'dragon fruits',
    'dades',
    'mango',
    'fig',
    'mallberry',
    'papaya',
    'grapefruites',
    'guava',
    'starfruite',
    'crunberry',
    'rose hip',
];
$fruites4 = [
    'apple',
    'pear',
    'orange',
    'banana',
    'kiwi',
    'pomogranate',
    'strawberry',
    'lime',
    'lemon',
    'blueberry',
    'rawberry',
    'grapes',
    'coconuts',
    'pineapples',
    'watermelon',
    'melon',
    'mandarin',
    'peach',
    'plum',
    'cherry',
    'blackerry',
    'apricot',
    'dragon fruits',
    'dades',
    'mango',
    'fig',
    'mallberry',
    'papaya',
    'grapefruites',
    'guava',
    'starfruite',
    'crunberry',
    'rose hip',
];
$fruites5 = [
    'apple',
    'pear',
    'orange',
    'banana',
    'kiwi',
    'pomogranate',
    'strawberry',
    'lime',
    'lemon',
    'blueberry',
    'rawberry',
    'grapes',
    'coconuts',
    'pineapples',
    'watermelon',
    'melon',
    'mandarin',
    'peach',
    'plum',
    'cherry',
    'blackerry',
    'apricot',
    'dragon fruits',
    'dades',
    'mango',
    'fig',
    'mallberry',
    'papaya',
    'grapefruites',
    'guava',
    'starfruite',
    'crunberry',
    'rose hip',
];
$fruites6 = [
    'apple',
    'pear',
    'orange',
    'banana',
    'kiwi',
    'pomogranate',
    'strawberry',
    'lime',
    'lemon',
    'blueberry',
    'rawberry',
    'grapes',
    'coconuts',
    'pineapples',
    'watermelon',
    'melon',
    'mandarin',
    'peach',
    'plum',
    'cherry',
    'blackerry',
    'apricot',
    'dragon fruits',
    'dades',
    'mango',
    'fig',
    'mallberry',
    'papaya',
    'grapefruites',
    'guava',
    'starfruite',
    'crunberry',
    'rose hip',
];
$fruites7 = [
    'apple',
    'pear',
    'orange',
    'banana',
    'kiwi',
    'pomogranate',
    'strawberry',
    'lime',
    'lemon',
    'blueberry',
    'rawberry',
    'grapes',
    'coconuts',
    'pineapples',
    'watermelon',
    'melon',
    'mandarin',
    'peach',
    'plum',
    'cherry',
    'blackerry',
    'apricot',
    'dragon fruits',
    'dades',
    'mango',
    'fig',
    'mallberry',
    'papaya',
    'grapefruites',
    'guava',
    'starfruite',
    'crunberry',
    'rose hip',
];
$fruites8 = [
    'apple',
    'pear',
    'orange',
    'banana',
    'kiwi',
    'pomogranate',
    'strawberry',
    'lime',
    'lemon',
    'blueberry',
    'rawberry',
    'grapes',
    'coconuts',
    'pineapples',
    'watermelon',
    'melon',
    'mandarin',
    'peach',
    'plum',
    'cherry',
    'blackerry',
    'apricot',
    'dragon fruits',
    'dades',
    'mango',
    'fig',
    'mallberry',
    'papaya',
    'grapefruites',
    'guava',
    'starfruite',
    'crunberry',
    'rose hip',
];
$fruites9 = [
    'apple',
    'pear',
    'orange',
    'banana',
    'kiwi',
    'pomogranate',
    'strawberry',
    'lime',
    'lemon',
    'blueberry',
    'rawberry',
    'grapes',
    'coconuts',
    'pineapples',
    'watermelon',
    'melon',
    'mandarin',
    'peach',
    'plum',
    'cherry',
    'blackerry',
    'apricot',
    'dragon fruits',
    'dades',
    'mango',
    'fig',
    'mallberry',
    'papaya',
    'grapefruites',
    'guava',
    'starfruite',
    'crunberry',
    'rose hip',
];
$fruites10 = [
    'apple',
    'pear',
    'orange',
    'banana',
    'kiwi',
    'pomogranate',
    'strawberry',
    'lime',
    'lemon',
    'blueberry',
    'rawberry',
    'grapes',
    'coconuts',
    'pineapples',
    'watermelon',
    'melon',
    'mandarin',
    'peach',
    'plum',
    'cherry',
    'blackerry',
    'apricot',
    'dragon fruits',
    'dades',
    'mango',
    'fig',
    'mallberry',
    'papaya',
    'grapefruites',
    'guava',
    'starfruite',
    'crunberry',
    'rose hip',
];
$fruites = array_merge(
    $fruites1,
    $fruites2,
    $fruites3,
    $fruites4,
    $fruites5,
    $fruites6,
    $fruites7,
    $fruites8,
    $fruites9,
    $fruites10
);

$newfruits = [];

foreach ($fruites as $jon => $iowa) {
    if (($jon-23)>0) {
        if ($jon % 2 == 0) {
            if ($jon % 5 == 0) {
                if ($jon % 7 == 0) {
                    if ($jon % 140 == 0) {
                        $newfruits[$jon] = $iowa;
                    }
                }
            }
        }
    }
}
echo "<pre>";
print_r ($newfruits);


?>
