<?php
namespace Gilbane;
require_once 'GeneralConstrution.php';
require_once 'rules.php';
class electrical extends GeneralConstrution implements Rules
{
    public function clothes()
    {
        return "Everybody use hardheat,glasses,vest,highvisiblity shirts,jeans,boots.";
    }

    public function lunchTime()
    {
        return "Lunch time start 12:00pm by 3:00pm also coffee time 09:00am by 09:00am";
    }

    public function workingTimes()
    {
        return "working times start 07:00am by 03:00pm Monday by Friday also Saturday and Sunday off";
    }

    public function RespectColleagues()
    {
        return "Respect the workers , be polay,dont cursing,not discrimination";
    }

    public function emergency()
    {
        return "Anybody has accident and feeling sick let GS knows";
    }
    public function electricalSalary()
    {
        return parent::electricalSalary(); // TODO: Change the autogenerated stub
    }
}
$electrical = new electrical();
$electrical->electrical();
echo "<hr>";
echo $electrical->electricalSalary();
echo "<hr>";

