<?php
namespace Gilbane;
require_once 'GeneralConstrution.php';
require_once 'rules.php';
class labor extends GeneralConstrution implements Rules {
    public function clothes()
    {
        parent::clothes(); // TODO: Change the autogenerated stub
    }
    public function lunchTime()
    {
        parent::lunchTime(); // TODO: Change the autogenerated stub
    }
    public function workingTimes()
    {
        parent::workingTimes(); // TODO: Change the autogenerated stub
    }
    public function RespectColleagues()
    {
        parent::RespectColleagues(); // TODO: Change the autogenerated stub
    }
    public function emergency()
    {
        parent::emergency(); // TODO: Change the autogenerated stub
    }
}

