<?php
namespace Gilbane;
require_once 'GeneralConstrution.php';
require_once 'rules.php';
class plumbing extends GeneralConstrution implements Rules {
    use \DOB;
    public function clothes()
    {
        return "Everybody use hardheat,glasses,vest,highvisiblity shirts,jeans,boots.";
    }
    public function lunchTime()
    {
        return "Lunch time start 12:00pm by 3:00pm also coffee time 09:00am by 09:00am";
    }
    public function workingTimes()
    {
        return "working times start 07:00am by 03:00pm Monday by Friday also Saturday and Sunday off";
    }
    public function RespectColleagues()
    {
        return "Respect the workers , be polay,dont cursing,not discrimination";
    }
    public function emergency()
    {
        return "Anybody has accident and feeling sick let GS knows";
    }
    public function plumbingSalary()
    {
        return parent::plumbingSalary(); // TODO: Change the autogenerated stub
    }
}
$plumbing = new plumbing();
echo $plumbing->plumbing();
echo "<hr>";
echo $plumbing->plumbingSalary();
echo "<hr>";
echo $plumbing->emergency();
echo "<hr>";
echo $plumbing->workingTimes();
echo "<hr>";
echo $plumbing->RespectColleagues();
echo "<hr>";
echo $plumbing->clothes();
echo "<hr>";
echo $plumbing->lunchTime();
echo "<hr>";
echo $plumbing->gasCode();