<?php
namespace Tashevs;
require_once 'parents.php';
class Farzand extends Parents{
    public function otaOnaOyligi(){
    }
    public function oqitibKattaQilish()
    {
        return parent::oqitibKattaQilish(); // TODO: Change the autogenerated stub
    }

}
$farzand = new Farzand();
echo $farzand->tarbiyaBerish();
echo "<hr>";
echo $farzand->oqitibKattaQilish();
echo "<hr>";
echo $farzand->oqitibQoyish();
echo "<hr>";
echo $farzand->otaOnaOyligi();
echo "<hr>";